// react/src/views/signIn.jsx
import React, { useState } from 'react';
import PropTypes from 'prop-types';
import { Formik, Form } from 'formik';
import * as Yup from 'yup';

import { Logo } from '../components/logo';
import { Title } from '../components/title';
import { Field } from '../components/field';
import authentication from '../services/authentication';

const signInSchema = Yup.object().shape({
  email: Yup
    .string()
    .email('Invalid email')
    .required('Email is required'),
  password: Yup
    .string()
    .required('Password is required')
    .matches(/\w{6,}/, 'Password must be at least 6 characters')
});

export function SignIn(props) {
  const [error, setError] = useState('');

  const handleSubmit = ({ email, password }) => {
    authentication.login(email, password).then(
      () => props.history.push('/movies'),
      () => setError('Invalid email and password combination')
    );
  };

  return (
    <div className="container sign-in">
      <div className="row">
        <div className="center">
          <Logo />
        </div>
      </div>
      <div className="row">
        <div className="center">
          <Title title="Sign In" />
        </div>
      </div>
      {error &&
        <div className="row">
          <div className="center red-text">{error}</div>
        </div>
      }
      <Formik validationSchema={signInSchema} component={SignInForm} onSubmit={handleSubmit} />
      <div className="row">
        <div className="center dark-text">
          Don't have account? Sign up <span className="highlight-text pointer" onClick={() => props.history.push('/signup')}>here</span>.
        </div>
      </div>
    </div>
  );
}

function SignInForm({ handleChange, handleBlur, values, touched, errors, isValid }) {
  return (
    <Form>
      <div className="row">
        <div className="col s12 offset-m3 m6 offset-l4 l4">
          <Field
            name="email"
            type="email"
            error={errors.email}
            touched={touched.email}
            value={values.email}
            onChange={handleChange}
            onBlur={handleBlur}
          />
        </div>
      </div>
      <div className="row">
        <div className="col s12 offset-m3 m6 offset-l4 l4">
          <Field
            name="password"
            type="password"
            error={errors.password}
            touched={touched.password}
            value={values.password}
            onChange={handleChange}
            onBlur={handleBlur}
          />
        </div>
      </div>
      <div className="row">
        <div className="col s12 offset-m3 m6 offset-l4 l4">
          <button
            type="submit"
            className={"waves-effect waves-light btn btn-primary full-width" + (!isValid ? " disabled" : "")} 
          >
            sign in
          </button>
        </div>
      </div>
    </Form>
  )
}

SignIn.propTypes = {
  history: PropTypes.object
};

// vue/src/views/auth/SignIn.vue
<template>
  <div class="container sign-in">
    <div class="row">
      <div class="center">
        <logo />
      </div>
    </div>
    <div class="row">
      <div class="center">
        <Header class="title" name="Login">Sign In</Header>
      </div>
    </div>
    <form @submit.prevent="login()">
      <div class="row">
        <div class="col s12 offset-m3 m6 offset-l4 l4">
          <Input
            v-model="email"
            :valid="validEmail"
            name="Email"
            type="email"
            error="Invalid email"
          />
        </div>
      </div>
      <div class="row">
        <div class="col s12 offset-m3 m6 offset-l4 l4">
          <Input
            v-model="password"
            :valid="validPassword"
            name="Password"
            type="password"
            error="Password is required"
          />
        </div>
      </div>
      <div class="row">
        <div class="col s12 offset-m3 m6 offset-l4 l4">
          <Button
            class="waves-effect waves-light btn btn-primary full-width"
            :class="{ disabled:isValid }"
            name="Login"
          />
        </div>
      </div>
    </form>
    <div class="row">
      <div class="center dark-text">
        Don't have account? Sign up
        <span class="highlight-text pointer">
          <router-link to="/signup">here</router-link>
        </span>.
      </div>
    </div>
  </div>
</template>

<script>
import FunctionUtils from "../../mixins/function-util";

import { mapActions } from "vuex";

import { authService } from "../../services/authService";

import Logo from "../../components/images/Logo";
import Header from "../../components/shared/Header";
import Input from "../../components/shared/Input";
import Button from "../../components/shared/Button";

export default {
  mixins: [FunctionUtils],
  data() {
    return {
      email: "",
      password: ""
    };
  },
  computed: {
    validEmail() {
      return this.validateEmail(this.email);
    },
    validPassword() {
      return this.validatePassword(this.password);
    },
    isValid() {
      return (
        !this.validateEmail(this.email) || !this.validatePassword(this.password)
      );
    }
  },
  methods: {
    ...mapActions(["setUser"]),
    login() {
      if (this.isValid) {
        return;
      }
      authService
        .login(this.email, this.password)
        .then(response => {
          this.setUser(response.data);
        })
        .finally(() => {
          this.$router.push({ path: "list" });
        });
    }
  },
  components: {
    Logo,
    Header,
    Input,
    Button
  }
};
</script>

<style lang="scss" scoped>
.login-form {
}
</style>
