// react/src/components/movies/trailer.jsx
import React from 'react';
import PropTypes from 'prop-types';

export function Trailer(props) {
  const { innerWidth, innerHeight } = window;
  return (
    <>
      <div className="trailer-backdrop" onClick={props.onClose} />
      {props.loading ?
        <div className="loader" /> :
        <iframe
          title={props.youtubeId}
          width={innerWidth / 2}
          height={innerHeight / 2}
          src={`https://www.youtube.com/embed/${props.youtubeId}`}
          frameBorder="0"
          allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
        />
      }
    </>
  )
}

Trailer.propTypes = {
  youtubeId: PropTypes.string,
  loading: PropTypes.bool,
  onClose: PropTypes.func
};

Trailer.defaultProps = {
  youtubeId: '',
  loading: false
};

// angular/src/app/modules/movies/components/trailer/trailer.component.ts
import { Component, Inject, OnInit } from '@angular/core';
import { MAT_DIALOG_DATA } from '@angular/material';
import { DomSanitizer, SafeResourceUrl } from '@angular/platform-browser';

@Component({
  selector: 'app-trailer',
  templateUrl: './trailer.component.html'
})
export class TrailerComponent implements OnInit {

  private YOUTUBE_EMBED_URL = 'https://www.youtube.com/embed/';

  public safeUrl: SafeResourceUrl;
  public innerWidth: number;
  public innerHeight: number;
  
  constructor(
    @Inject(MAT_DIALOG_DATA) public data: any,
    private sanitizer: DomSanitizer
  ) { }

  ngOnInit() {
    this.innerWidth = window.innerWidth;
    this.innerHeight = window.innerHeight;
    this.safeUrl = this.sanitizer.bypassSecurityTrustResourceUrl(`${this.YOUTUBE_EMBED_URL}${this.data.youtubeId}`);
  }
}

<div class="gof-trailer-container">
    <iframe
        title="Test"
        [width]="innerWidth / 2"
        [height]="innerHeight / 2"
        [src]="safeUrl"
        frameborder="0">
    </iframe>
</div>
